### ISSUE TITLE
Background Subtraction in Skeltrack 

### ISSUE THREAD

**Issue by ChengYaoWang** [joaquimrocha/Skeltrack#25]
Hello everyone, 

I have read the paper "A Data-Driven Approach for Real-Time Full Body Pose Reconstruction
from a Depth Camera" and review the source code of Skeltrack. However, I can't find the background subtraction part in Skeltrack. 

In my current project, I'd like to use other background subtraction algorithm to get better result. I'd like to know if Skeltrack use the similar method in the paper for background subtraction (create a static prerecorded background model).  

Best Regards,
Eric Wang.

**Comment by joaquimrocha** [comment]
Hi Eric,

[By the way, this is a not really an issue. For questions like this you should contact me or @iaguis directly]

Skeltrack does not use background subtraction. We do use a depth threshold in order to just skip all non-interesting data that might be part of the background but that's a different matter.

If you're talking about 2D background subtraction, that's not difficult to accomplish but you can also use OpenCV for that: http://docs.opencv.org/master/db/d5c/tutorial_py_bg_subtraction.html

The challenge in doing 3D background (in case that's what you need) with a structured-lighting cam like the Kinect is that the values are not static from frame to frame so you'd need to maybe smooth the data.

**Comment by ChengYaoWang** [comment]
Hi Joaquim,

Thanks for your quick response. So we can use  the THRESHOLD_BEGIN and
THRESHOLD_END in the process_buffer() to skip all non-interesting data,
right?

By the way, Skeltrack is really awesome. In my current project, I used
Skeltrack with Kinect to get the skeleton data for gesture recognition.
However, we put the Kinect on a robot, when the robot move, the skeleton
data will lost immediately. I'm try to figure out how to solve the problem
:)

Thanks for your time and help.

Best Regards,
Eric Wang
